# Generated by Django 3.1.2 on 2020-10-05 15:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MuscleFeed_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='agreed_error_en',
            new_name='agreed_error_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='agreed_en',
            new_name='agreed_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='bad_key_en',
            new_name='bad_key_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='confirm_instruction_en',
            new_name='confirm_instruction_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='email_confirmed_en',
            new_name='email_confirmed_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='error_email_exists_en',
            new_name='error_email_exists_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='error_en',
            new_name='error_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='error_no_register_data_en',
            new_name='error_no_register_data_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='error_phone_exists_en',
            new_name='error_phone_exists_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='error_phone_russia_en',
            new_name='error_phone_russia_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='error_phone_short_en',
            new_name='error_phone_short_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='forget_password_en',
            new_name='forget_password_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='key_info_en',
            new_name='key_info_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='key_resented_en',
            new_name='key_resented_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='language_en',
            new_name='language_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='logging_in_en',
            new_name='logging_in_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='login_en',
            new_name='login_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='logout_en',
            new_name='logout_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='next_en',
            new_name='next_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='no_such_email_en',
            new_name='no_such_email_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='password_en',
            new_name='password_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='personal_account_en',
            new_name='personal_account_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='please_login_en',
            new_name='please_login_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='registration_en',
            new_name='registration_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='remember_me_en',
            new_name='remember_me_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='repeat_password_en',
            new_name='repeat_password_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='resend_key_en',
            new_name='resend_key_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='reset_password_en',
            new_name='reset_password_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='rules_en',
            new_name='rules_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='signup_by_email_en',
            new_name='signup_by_email_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='signup_by_phone_en',
            new_name='signup_by_phone_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='success_en',
            new_name='success_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='try_again_en',
            new_name='try_again_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='user_login_en',
            new_name='user_login_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='user_middlename_en',
            new_name='user_middlename_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='user_name_en',
            new_name='user_name_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='user_phone_en',
            new_name='user_phone_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='user_sex_en',
            new_name='user_sex_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='user_surname_en',
            new_name='user_surname_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='wait_a_second_en',
            new_name='wait_a_second_he',
        ),
        migrations.RenameField(
            model_name='wrappertranslations',
            old_name='wrong_password_en',
            new_name='wrong_password_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='keywords',
        ),
        migrations.AddField(
            model_name='fixed',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Логотип сайта'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_site_name',
            field=models.CharField(default='', help_text='Поисковик', max_length=50,
                                   verbose_name='Open Graph название сайта'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_site_name_he',
            field=models.CharField(default='', help_text='Поисковик', max_length=50, null=True,
                                   verbose_name='Open Graph название сайта'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_site_name_ru',
            field=models.CharField(default='', help_text='Поисковик', max_length=50, null=True,
                                   verbose_name='Open Graph название сайта'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='separator',
            field=models.CharField(default='|', help_text='Google.com | Поиск (Тут "|")', max_length=10,
                                   verbose_name='Разделитель Title'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True,
                                   verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meta_description_he',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True,
                                   verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True,
                                   verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meta_keywords_he',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_description',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_description_he',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_description_ru',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_image',
            field=models.ImageField(blank=True, help_text='Используется в SEO', null=True, upload_to='images',
                                    verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_image_he',
            field=models.ImageField(blank=True, help_text='Используется в SEO', null=True, upload_to='images',
                                    verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_image_ru',
            field=models.ImageField(blank=True, help_text='Используется в SEO', null=True, upload_to='images',
                                    verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_title',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_title_he',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='open_graph_title_ru',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_description',
            field=models.CharField(blank=True, max_length=120, null=True,
                                   verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_description_he',
            field=models.CharField(blank=True, max_length=120, null=True,
                                   verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_description_ru',
            field=models.CharField(blank=True, max_length=120, null=True,
                                   verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_image_1',
            field=models.ImageField(blank=True, help_text='Большого размера (1920x1080)', null=True,
                                    upload_to='images/slider/', verbose_name='Изображение для главного слайдера №1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_image_2',
            field=models.ImageField(blank=True, help_text='Большого размера (1920x1080)', null=True,
                                    upload_to='images/slider/', verbose_name='Изображение для главного слайдера №2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_image_3',
            field=models.ImageField(blank=True, help_text='Большого размера (1920x1080)', null=True,
                                    upload_to='images/slider/', verbose_name='Изображение для главного слайдера №3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_image_4',
            field=models.ImageField(blank=True, help_text='Большого размера (1920x1080)', null=True,
                                    upload_to='images/slider/', verbose_name='Изображение для главного слайдера №4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_image_5',
            field=models.ImageField(blank=True, help_text='Большого размера (1920x1080)', null=True,
                                    upload_to='images/slider/', verbose_name='Изображение для главного слайдера №5'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_overlay',
            field=models.PositiveSmallIntegerField(default='40', help_text='0-99', verbose_name='Затемнение слайдера'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_title',
            field=models.CharField(blank=True, help_text='2-5 слов', max_length=40, null=True,
                                   verbose_name='Большой текст на слайдере'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_title_he',
            field=models.CharField(blank=True, help_text='2-5 слов', max_length=40, null=True,
                                   verbose_name='Большой текст на слайдере'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_title_ru',
            field=models.CharField(blank=True, help_text='2-5 слов', max_length=40, null=True,
                                   verbose_name='Большой текст на слайдере'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='title_he',
            field=models.CharField(help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Заголовок страницы (Meta Title)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='title_ru',
            field=models.CharField(help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Заголовок страницы (Meta Title)'),
        ),
        migrations.AddField(
            model_name='rules',
            name='content_he',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Правила'),
        ),
        migrations.AddField(
            model_name='rules',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Правила'),
        ),
        migrations.AddField(
            model_name='rules',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True,
                                   verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='rules',
            name='meta_description_he',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True,
                                   verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='rules',
            name='meta_description_ru',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True,
                                   verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='rules',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='rules',
            name='meta_keywords_he',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='rules',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, help_text='Используется в SEO', null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_description',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_description_he',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_description_ru',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_image',
            field=models.ImageField(blank=True, help_text='Используется в SEO', null=True, upload_to='images',
                                    verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_image_he',
            field=models.ImageField(blank=True, help_text='Используется в SEO', null=True, upload_to='images',
                                    verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_image_ru',
            field=models.ImageField(blank=True, help_text='Используется в SEO', null=True, upload_to='images',
                                    verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_title',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_title_he',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='rules',
            name='open_graph_title_ru',
            field=models.CharField(blank=True, help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='rules',
            name='title',
            field=models.CharField(default=0, help_text='Используется в SEO', max_length=200,
                                   verbose_name='Заголовок страницы (Meta Title)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='title_he',
            field=models.CharField(help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Заголовок страницы (Meta Title)'),
        ),
        migrations.AddField(
            model_name='rules',
            name='title_ru',
            field=models.CharField(help_text='Используется в SEO', max_length=200, null=True,
                                   verbose_name='Заголовок страницы (Meta Title)'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='key',
            field=models.CharField(max_length=6, verbose_name='Ключ подтверждения'),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='base',
            field=models.CharField(help_text='Например: Google.com', max_length=100, verbose_name='Домен сайта'),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='icon',
            field=models.ImageField(blank=True, help_text='180x180, формат png или jpg', null=True, upload_to='icons',
                                    verbose_name='Иконка сайта'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='title',
            field=models.CharField(help_text='Используется в SEO', max_length=200,
                                   verbose_name='Заголовок страницы (Meta Title)'),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='key',
            field=models.CharField(max_length=6, verbose_name='Ключ подтверждения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('he', 'Иврит')], default='en', max_length=2,
                                   verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='resetpasswordverification',
            name='key',
            field=models.CharField(max_length=6, verbose_name='Ключ подтверждения'),
        ),
    ]
