# Generated by Django 3.1.2 on 2020-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MuscleFeed_main', '0003_fixed_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description',
            field=models.CharField(blank=True, help_text='Для переноса строки используйте <br>', max_length=120,
                                   null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description_he',
            field=models.CharField(blank=True, help_text='Для переноса строки используйте <br>', max_length=120,
                                   null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description_ru',
            field=models.CharField(blank=True, help_text='Для переноса строки используйте <br>', max_length=120,
                                   null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_overlay',
            field=models.PositiveSmallIntegerField(default='75', help_text='0-99', verbose_name='Затемнение слайдера'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_title',
            field=models.CharField(blank=True, help_text='Для переноса строки используйте <br>', max_length=40,
                                   null=True, verbose_name='Большой текст на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_title_he',
            field=models.CharField(blank=True, help_text='Для переноса строки используйте <br>', max_length=40,
                                   null=True, verbose_name='Большой текст на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_title_ru',
            field=models.CharField(blank=True, help_text='Для переноса строки используйте <br>', max_length=40,
                                   null=True, verbose_name='Большой текст на слайдере'),
        ),
    ]
