# Generated by Django 3.1.2 on 2020-10-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MuscleFeed_main', '0004_auto_20201005_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='slider_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='slider_description_ru',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses1_description',
            field=models.CharField(
                default='С нашим сервисом вы сэкономите кучу времени на походах в магазин и приготовление пищи. Больше не надо готовить!',
                max_length=200, verbose_name='Описание преимущества №1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses1_description_he',
            field=models.CharField(
                default='С нашим сервисом вы сэкономите кучу времени на походах в магазин и приготовление пищи. Больше не надо готовить!',
                max_length=200, null=True, verbose_name='Описание преимущества №1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses1_description_ru',
            field=models.CharField(
                default='С нашим сервисом вы сэкономите кучу времени на походах в магазин и приготовление пищи. Больше не надо готовить!',
                max_length=200, null=True, verbose_name='Описание преимущества №1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses1_icon',
            field=models.CharField(default='fas fa-clock', max_length=40,
                                   verbose_name='Иконка первого преимущества (класс fontawesome 5)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses1_title',
            field=models.CharField(default='Не надо готовки', max_length=20, verbose_name='Название преимущества №1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses1_title_he',
            field=models.CharField(default='Не надо готовки', max_length=20, null=True,
                                   verbose_name='Название преимущества №1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses1_title_ru',
            field=models.CharField(default='Не надо готовки', max_length=20, null=True,
                                   verbose_name='Название преимущества №1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses2_description',
            field=models.CharField(
                default='Если вы всегда мечтали вкусно питаться и оставаться в форме - это лучший вариант для вас. Выберите план питания и наслаждайтесь жизнью, не ограничивая себя!',
                max_length=200, verbose_name='Описание преимущества №2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses2_description_he',
            field=models.CharField(
                default='Если вы всегда мечтали вкусно питаться и оставаться в форме - это лучший вариант для вас. Выберите план питания и наслаждайтесь жизнью, не ограничивая себя!',
                max_length=200, null=True, verbose_name='Описание преимущества №2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses2_description_ru',
            field=models.CharField(
                default='Если вы всегда мечтали вкусно питаться и оставаться в форме - это лучший вариант для вас. Выберите план питания и наслаждайтесь жизнью, не ограничивая себя!',
                max_length=200, null=True, verbose_name='Описание преимущества №2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses2_icon',
            field=models.CharField(default='fas fa-weight', max_length=40,
                                   verbose_name='Иконка второго преимущества (класс fontawesome 5)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses2_title',
            field=models.CharField(default='Оставайтесь в форме', max_length=20,
                                   verbose_name='Название преимущества №2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses2_title_he',
            field=models.CharField(default='Оставайтесь в форме', max_length=20, null=True,
                                   verbose_name='Название преимущества №2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses2_title_ru',
            field=models.CharField(default='Оставайтесь в форме', max_length=20, null=True,
                                   verbose_name='Название преимущества №2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses3_description',
            field=models.CharField(
                default='Наша продукция изготавлевается из натуральных материалов и имеет оптимальные для вас параметры. Забудьте о проблемах с пищеварением!',
                max_length=200, verbose_name='Описание преимущества №3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses3_description_he',
            field=models.CharField(
                default='Наша продукция изготавлевается из натуральных материалов и имеет оптимальные для вас параметры. Забудьте о проблемах с пищеварением!',
                max_length=200, null=True, verbose_name='Описание преимущества №3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses3_description_ru',
            field=models.CharField(
                default='Наша продукция изготавлевается из натуральных материалов и имеет оптимальные для вас параметры. Забудьте о проблемах с пищеварением!',
                max_length=200, null=True, verbose_name='Описание преимущества №3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses3_icon',
            field=models.CharField(default='fas fa-heartbeat', max_length=40,
                                   verbose_name='Иконка третьего преимущества (класс fontawesome 5)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses3_title',
            field=models.CharField(default='Правильное питание', max_length=20,
                                   verbose_name='Название преимущества №3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses3_title_he',
            field=models.CharField(default='Правильное питание', max_length=20, null=True,
                                   verbose_name='Название преимущества №3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='pluses3_title_ru',
            field=models.CharField(default='Правильное питание', max_length=20, null=True,
                                   verbose_name='Название преимущества №3'),
        ),
    ]
