# Generated by Django 3.1.2 on 2020-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MuscleFeed_main', '0005_auto_20201006_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_calories',
            field=models.CharField(default='от 800 ккал', max_length=30, verbose_name='Калорийность плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_description',
            field=models.CharField(default='Избавляйтесь от лишних килограмм, вкусно и без вреда для здоровья.',
                                   max_length=200, verbose_name='Описание плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_description_he',
            field=models.CharField(default='Избавляйтесь от лишних килограмм, вкусно и без вреда для здоровья.',
                                   max_length=200, null=True, verbose_name='Описание плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_description_ru',
            field=models.CharField(default='Избавляйтесь от лишних килограмм, вкусно и без вреда для здоровья.',
                                   max_length=200, null=True, verbose_name='Описание плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/plans/',
                                    verbose_name='Фоновое изображение плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_name',
            field=models.CharField(default='Сбросить вес', max_length=30, verbose_name='Название плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_name_he',
            field=models.CharField(default='Сбросить вес', max_length=30, null=True, verbose_name='Название плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_name_ru',
            field=models.CharField(default='Сбросить вес', max_length=30, null=True, verbose_name='Название плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_short_description',
            field=models.CharField(default='-6 кг за 3 недели', max_length=30,
                                   verbose_name='Короткое описание плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_short_description_he',
            field=models.CharField(default='-6 кг за 3 недели', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_short_description_ru',
            field=models.CharField(default='-6 кг за 3 недели', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_calories',
            field=models.CharField(default='от 2000 ккал', max_length=30, verbose_name='Калорийность плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_calories_he',
            field=models.CharField(default='от 2000 ккал', max_length=30, null=True,
                                   verbose_name='Калорийность плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_calories_ru',
            field=models.CharField(default='от 2000 ккал', max_length=30, null=True,
                                   verbose_name='Калорийность плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_description',
            field=models.CharField(
                default='Поддерживайте текущий вес, соблюдая все дневные нормы нутриентов и витаминов.', max_length=200,
                verbose_name='Описание плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_description_he',
            field=models.CharField(
                default='Поддерживайте текущий вес, соблюдая все дневные нормы нутриентов и витаминов.', max_length=200,
                null=True, verbose_name='Описание плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_description_ru',
            field=models.CharField(
                default='Поддерживайте текущий вес, соблюдая все дневные нормы нутриентов и витаминов.', max_length=200,
                null=True, verbose_name='Описание плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/plans/',
                                    verbose_name='Фоновое изображение плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_name',
            field=models.CharField(default='Оставаться в форме', max_length=30, verbose_name='Название плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_name_he',
            field=models.CharField(default='Оставаться в форме', max_length=30, null=True,
                                   verbose_name='Название плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_name_ru',
            field=models.CharField(default='Оставаться в форме', max_length=30, null=True,
                                   verbose_name='Название плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_short_description',
            field=models.CharField(default='Стабильный вес', max_length=30, verbose_name='Короткое описание плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_short_description_he',
            field=models.CharField(default='Стабильный вес', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan2_short_description_ru',
            field=models.CharField(default='Стабильный вес', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 2'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_calories',
            field=models.CharField(default='от 2500 ккал', max_length=30, verbose_name='Калорийность плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_calories_he',
            field=models.CharField(default='от 2500 ккал', max_length=30, null=True,
                                   verbose_name='Калорийность плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_calories_ru',
            field=models.CharField(default='от 2500 ккал', max_length=30, null=True,
                                   verbose_name='Калорийность плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_description',
            field=models.CharField(
                default='Увеличивайте свои объемы, питаясь вкусными и разнообразными блюдами каждый день.',
                max_length=300, verbose_name='Описание плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_description_he',
            field=models.CharField(
                default='Увеличивайте свои объемы, питаясь вкусными и разнообразными блюдами каждый день.',
                max_length=300, null=True, verbose_name='Описание плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_description_ru',
            field=models.CharField(
                default='Увеличивайте свои объемы, питаясь вкусными и разнообразными блюдами каждый день.',
                max_length=300, null=True, verbose_name='Описание плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/plans/',
                                    verbose_name='Фоновое изображение плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_name',
            field=models.CharField(default='Набрать мышечную массу', max_length=30, verbose_name='Название плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_name_he',
            field=models.CharField(default='Набрать мышечную массу', max_length=30, null=True,
                                   verbose_name='Название плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_name_ru',
            field=models.CharField(default='Набрать мышечную массу', max_length=30, null=True,
                                   verbose_name='Название плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_short_description',
            field=models.CharField(default='Полезно для мышц', max_length=30, verbose_name='Короткое описание плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_short_description_he',
            field=models.CharField(default='Полезно для мышц', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan3_short_description_ru',
            field=models.CharField(default='Полезно для мышц', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 3'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_calories',
            field=models.CharField(default='от 1500 ккал', max_length=30, verbose_name='Калорийность плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_calories_he',
            field=models.CharField(default='от 1500 ккал', max_length=30, null=True,
                                   verbose_name='Калорийность плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_calories_ru',
            field=models.CharField(default='от 1500 ккал', max_length=30, null=True,
                                   verbose_name='Калорийность плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_description',
            field=models.CharField(default='Полноценно и полезно, не употребления в пищу мясо животного происхождения',
                                   max_length=400, verbose_name='Описание плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_description_he',
            field=models.CharField(default='Полноценно и полезно, не употребления в пищу мясо животного происхождения',
                                   max_length=400, null=True, verbose_name='Описание плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_description_ru',
            field=models.CharField(default='Полноценно и полезно, не употребления в пищу мясо животного происхождения',
                                   max_length=400, null=True, verbose_name='Описание плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/plans/',
                                    verbose_name='Фоновое изображение плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_name',
            field=models.CharField(default='Вегатерианское питание', max_length=30, verbose_name='Название плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_name_he',
            field=models.CharField(default='Вегатерианское питание', max_length=30, null=True,
                                   verbose_name='Название плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_name_ru',
            field=models.CharField(default='Вегатерианское питание', max_length=30, null=True,
                                   verbose_name='Название плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_short_description',
            field=models.CharField(default='Без мяса', max_length=30, verbose_name='Короткое описание плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_short_description_he',
            field=models.CharField(default='Без мяса', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 4'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan4_short_description_ru',
            field=models.CharField(default='Без мяса', max_length=30, null=True,
                                   verbose_name='Короткое описание плана 4'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses1_description',
            field=models.CharField(
                default='С нашим сервисом вы сэкономите кучу времени на походах в магазин и приготовлении пищи. Больше не надо готовить!',
                max_length=200, verbose_name='Описание преимущества №1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses1_description_he',
            field=models.CharField(
                default='С нашим сервисом вы сэкономите кучу времени на походах в магазин и приготовлении пищи. Больше не надо готовить!',
                max_length=200, null=True, verbose_name='Описание преимущества №1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses1_description_ru',
            field=models.CharField(
                default='С нашим сервисом вы сэкономите кучу времени на походах в магазин и приготовлении пищи. Больше не надо готовить!',
                max_length=200, null=True, verbose_name='Описание преимущества №1'),
        ),
    ]
