# Generated by Django 3.1.2 on 2020-10-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MuscleFeed_main', '0006_auto_20201006_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя и фамилия автора отзыва')),
                ('name_ru',
                 models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя и фамилия автора отзыва')),
                ('name_he',
                 models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя и фамилия автора отзыва')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('content_ru', models.TextField(null=True, verbose_name='Отзыв')),
                ('content_he', models.TextField(null=True, verbose_name='Отзыв')),
                ('photo', models.ImageField(blank=True, help_text='Рекомендуемо: 100x100', null=True,
                                            upload_to='images/comments/', verbose_name='Фото автора отзыва')),
                ('url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на автора отзыва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('moderated', models.BooleanField(default=False, verbose_name='Одобрен')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
