# Generated by Django 3.1.2 on 2020-11-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0009_auto_20201103_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='add_middlename',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='add_middlename_he',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='add_middlename_ru',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='change_middlename',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='change_middlename_he',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='change_middlename_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_days_7',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_days_7_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_days_7_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='order_sale_7',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat1_count',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat1_icon',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat1_name',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat1_name_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat1_name_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat2_count',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat2_icon',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat2_name',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat2_name_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat2_name_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat3_count',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat3_icon',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat3_name',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat3_name_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stat3_name_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stats_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='stats_ru',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='wrappertranslations',
            name='user_middlename',
        ),
        migrations.RemoveField(
            model_name='wrappertranslations',
            name='user_middlename_he',
        ),
        migrations.RemoveField(
            model_name='wrappertranslations',
            name='user_middlename_ru',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_6',
            field=models.CharField(default='6 дней питания', max_length=200, verbose_name='6 дней питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_6_he',
            field=models.CharField(default='6 дней питания', max_length=200, null=True, verbose_name='6 дней питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_6_ru',
            field=models.CharField(default='6 дней питания', max_length=200, null=True, verbose_name='6 дней питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='order_sale_6',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=8, verbose_name='Скидка на заказ 6 дней'),
        ),
        migrations.AlterField(
            model_name='changepersonaldatarequest',
            name='type',
            field=models.CharField(choices=[('name', 'Имя'), ('surname', 'Фамилия'), ('phone', 'Телефон'), ('address', 'Адрес')], default='name', max_length=12, verbose_name='Тип'),
        ),
    ]
