# Generated by Django 3.1.2 on 2020-11-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0010_auto_20201105_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_description_he',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='slider_description_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
    ]
