# Generated by Django 3.1.2 on 2020-11-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0011_auto_20201106_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='delivery_map',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='images/maps/', verbose_name='Карта доставки'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery',
            field=models.CharField(default='Бесплатная доставка', max_length=200, verbose_name='Бесплатная доставка'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_he',
            field=models.CharField(default='Бесплатная доставка', max_length=200, null=True, verbose_name='Бесплатная доставка'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_ru',
            field=models.CharField(default='Бесплатная доставка', max_length=200, null=True, verbose_name='Бесплатная доставка'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_text_1',
            field=models.CharField(default='Доставим еду по Израилю бесплатно!', max_length=200, verbose_name='Доставим еду по Израилю бесплатно!'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_text_1_he',
            field=models.CharField(default='Доставим еду по Израилю бесплатно!', max_length=200, null=True, verbose_name='Доставим еду по Израилю бесплатно!'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_text_1_ru',
            field=models.CharField(default='Доставим еду по Израилю бесплатно!', max_length=200, null=True, verbose_name='Доставим еду по Израилю бесплатно!'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_text_2',
            field=models.CharField(default='Бесплатная доставка в выделенной области', max_length=200, verbose_name='Бесплатная доставка в выделенной области'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_text_2_he',
            field=models.CharField(default='Бесплатная доставка в выделенной области', max_length=200, null=True, verbose_name='Бесплатная доставка в выделенной области'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='free_delivery_text_2_ru',
            field=models.CharField(default='Бесплатная доставка в выделенной области', max_length=200, null=True, verbose_name='Бесплатная доставка в выделенной области'),
        ),
    ]
