# Generated by Django 3.1.2 on 2020-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0012_auto_20201111_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='delivery_map_he',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='images/maps/', verbose_name='Карта доставки'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='delivery_map_ru',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='images/maps/', verbose_name='Карта доставки'),
        ),
    ]
