# Generated by Django 3.1.2 on 2020-12-11 02:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0013_auto_20201111_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='easy_fit_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='gain_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='vegan_image',
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='active_fit_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='images/plans/account/', verbose_name='Active Fit план фоновое изображение'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='balance_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='images/plans/account/', verbose_name='Balance план фоновое изображение'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='vegeterian_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='images/plans/account/', verbose_name='Vegeterian план фоновое изображение'),
        ),
        migrations.AddField(
            model_name='dish',
            name='admin_name',
            field=models.CharField(default='0', max_length=50, verbose_name='Название для админа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(default='1', max_length=200, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='description_he',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='footer_info1',
            field=models.CharField(default='Фотографии блюд являются вариантом сервировки блюда. Внешний вид блюда может отличаться от фотографий на сайте', max_length=500, verbose_name='Фотографии блюд являются вариантом сервировки блюда. Внешний вид блюда может отличаться от фотографий на сайте'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='footer_info1_he',
            field=models.CharField(default='Фотографии блюд являются вариантом сервировки блюда. Внешний вид блюда может отличаться от фотографий на сайте', max_length=500, null=True, verbose_name='Фотографии блюд являются вариантом сервировки блюда. Внешний вид блюда может отличаться от фотографий на сайте'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='footer_info1_ru',
            field=models.CharField(default='Фотографии блюд являются вариантом сервировки блюда. Внешний вид блюда может отличаться от фотографий на сайте', max_length=500, null=True, verbose_name='Фотографии блюд являются вариантом сервировки блюда. Внешний вид блюда может отличаться от фотографий на сайте'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='footer_info2',
            field=models.CharField(default='Указывая номер телефона или e-mail на сайте, Вы соглашаетесь с условиями публичной оферты и обработки персональных данных', max_length=500, verbose_name='Указывая номер телефона или e-mail на сайте, Вы соглашаетесь с условиями публичной оферты и обработки персональных данных'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='footer_info2_he',
            field=models.CharField(default='Указывая номер телефона или e-mail на сайте, Вы соглашаетесь с условиями публичной оферты и обработки персональных данных', max_length=500, null=True, verbose_name='Указывая номер телефона или e-mail на сайте, Вы соглашаетесь с условиями публичной оферты и обработки персональных данных'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='footer_info2_ru',
            field=models.CharField(default='Указывая номер телефона или e-mail на сайте, Вы соглашаетесь с условиями публичной оферты и обработки персональных данных', max_length=500, null=True, verbose_name='Указывая номер телефона или e-mail на сайте, Вы соглашаетесь с условиями публичной оферты и обработки персональных данных'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses1_title',
            field=models.CharField(default='Не надо готовки', max_length=50, verbose_name='Название преимущества №1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses1_title_he',
            field=models.CharField(default='Не надо готовки', max_length=50, null=True, verbose_name='Название преимущества №1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses1_title_ru',
            field=models.CharField(default='Не надо готовки', max_length=50, null=True, verbose_name='Название преимущества №1'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses2_title',
            field=models.CharField(default='Оставайтесь в форме', max_length=50, verbose_name='Название преимущества №2'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses2_title_he',
            field=models.CharField(default='Оставайтесь в форме', max_length=50, null=True, verbose_name='Название преимущества №2'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses2_title_ru',
            field=models.CharField(default='Оставайтесь в форме', max_length=50, null=True, verbose_name='Название преимущества №2'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses3_title',
            field=models.CharField(default='Правильное питание', max_length=50, verbose_name='Название преимущества №3'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses3_title_he',
            field=models.CharField(default='Правильное питание', max_length=50, null=True, verbose_name='Название преимущества №3'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='pluses3_title_ru',
            field=models.CharField(default='Правильное питание', max_length=50, null=True, verbose_name='Название преимущества №3'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=120, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description_he',
            field=ckeditor.fields.RichTextField(blank=True, max_length=120, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, max_length=120, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Comfort Fit', 'Comfort Fit'), ('Active Fit', 'Active Fit'), ('Express Fit', 'Express Fit'), ('Balance', 'Balance'), ('Titan', 'Titan'), ('Vegeterian', 'Vegeterian')], max_length=50, verbose_name='Меню'),
        ),
    ]
