# Generated by Django 3.1.2 on 2020-12-11 02:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0014_auto_20201211_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=400, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description_he',
            field=ckeditor.fields.RichTextField(blank=True, max_length=400, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, max_length=400, null=True, verbose_name='Небольшое описание на слайдере'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='friday',
            field=models.ManyToManyField(blank=True, null=True, related_name='friday', to='MuscleFeed_main.Dish', verbose_name='Пятница стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='friday_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='friday_other', to='MuscleFeed_main.Dish', verbose_name='Пятница все блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='monday',
            field=models.ManyToManyField(blank=True, null=True, related_name='monday', to='MuscleFeed_main.Dish', verbose_name='Понедельник стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='monday_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='monday_other', to='MuscleFeed_main.Dish', verbose_name='Понедельник все блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='saturday',
            field=models.ManyToManyField(blank=True, null=True, related_name='saturday', to='MuscleFeed_main.Dish', verbose_name='Суббота стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='saturday_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='saturday_other', to='MuscleFeed_main.Dish', verbose_name='Суббота все блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sunday',
            field=models.ManyToManyField(blank=True, null=True, related_name='sunday', to='MuscleFeed_main.Dish', verbose_name='Воскресенье стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sunday_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='sunday_other', to='MuscleFeed_main.Dish', verbose_name='Воскресенье все блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thursday',
            field=models.ManyToManyField(blank=True, null=True, related_name='thursday', to='MuscleFeed_main.Dish', verbose_name='Четверг стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thursday_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='thursday_other', to='MuscleFeed_main.Dish', verbose_name='Четверг все блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tuesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='tuesday', to='MuscleFeed_main.Dish', verbose_name='Вторник стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tuesday_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='tuesday_other', to='MuscleFeed_main.Dish', verbose_name='Вторник все блюда'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='wednesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='wednesday', to='MuscleFeed_main.Dish', verbose_name='Среда стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='wednesday_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='wednesday_other', to='MuscleFeed_main.Dish', verbose_name='Среда все блюда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes_friday',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_friday', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда пятница'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes_monday',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_monday', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда понедельник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes_saturday',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_saturday', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда суббота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes_sunday',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_sunday', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда воскресенье'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes_thursday',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_thursday', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда четверг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes_tuesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_tuesday', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда вторник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes_wednesday',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_wednesday', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда среда'),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='MuscleFeed_main.Question', verbose_name='Вопросы'),
        ),
    ]
