# Generated by Django 3.1.2 on 2020-12-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0017_auto_20201213_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_calories_he',
            field=models.CharField(default='от 800 ккал', max_length=30, null=True, verbose_name='Калорийность плана 1'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='plan1_calories_ru',
            field=models.CharField(default='от 800 ккал', max_length=30, null=True, verbose_name='Калорийность плана 1'),
        ),
    ]
