# Generated by Django 3.1.2 on 2020-12-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0018_auto_20201214_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesettings',
            old_name='vegeterian_menu',
            new_name='vegetarian_menu',
        ),
        migrations.RenameField(
            model_name='homepagesettings',
            old_name='vegeterian_menu_he',
            new_name='vegetarian_menu_he',
        ),
        migrations.RenameField(
            model_name='homepagesettings',
            old_name='vegeterian_menu_ru',
            new_name='vegetarian_menu_ru',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='vegeterian_image',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='vegetarian_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='images/plans/account/', verbose_name='Vegetarian план фоновое изображение'),
        ),
        migrations.AddField(
            model_name='menu',
            name='friday_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Пятница цена (в мужской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='monday_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Понедельник цена (в мужской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='saturday_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Суббота цена (в мужской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='sunday_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Воскресенье цена (в мужской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='thursday_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Четверг цена (в мужской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='tuesday_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Вторник цена (в мужской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='wednesday_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Среда цена (в мужской версии)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Comfort Fit', 'Comfort Fit'), ('Active Fit', 'Active Fit'), ('Express Fit', 'Express Fit'), ('Balance', 'Balance'), ('Titan', 'Titan'), ('Vegetarian', 'Vegetarian')], max_length=50, verbose_name='Меню'),
        ),
    ]
