# Generated by Django 3.1.2 on 2020-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0020_question_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='friday_price',
            new_name='friday_price_male',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='monday_price',
            new_name='monday_price_male',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='saturday_price',
            new_name='saturday_price_male',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='sunday_price',
            new_name='sunday_price_male',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='thursday_price',
            new_name='thursday_price_male',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='tuesday_price',
            new_name='tuesday_price_male',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='wednesday_price',
            new_name='wednesday_price_male',
        ),
        migrations.AddField(
            model_name='menu',
            name='friday_price_female',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Пятница цена (в женской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='monday_price_female',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Понедельник цена (в женской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='saturday_price_female',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Суббота цена (в женской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='sunday_price_female',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Воскресенье цена (в женской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='thursday_price_female',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Четверг цена (в женской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='tuesday_price_female',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Вторник цена (в женской версии)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='wednesday_price_female',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=8, verbose_name='Среда цена (в женской версии)'),
            preserve_default=False,
        ),
    ]
