# Generated by Django 3.1.2 on 2020-12-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0023_auto_20201224_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed',
            name='whatsapp_number',
            field=models.PositiveBigIntegerField(help_text='В междунарожном формате, подробнее <a href="https://faq.whatsapp.com/general/chats/how-to-use-click-to-chat" target="_blank">тут</a>', verbose_name='WhatsApp номер'),
        ),
    ]
