# Generated by Django 3.1.2 on 2020-12-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0024_auto_20201224_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Ссылка на автора отзыва'),
        ),
    ]
