# Generated by Django 3.1.2 on 2020-12-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0026_auto_20201226_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='delivery_map_webp',
            field=models.ImageField(blank=True, editable=False, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='', verbose_name='Карта доставки webp'),
        ),
    ]
