# Generated by Django 3.1.2 on 2021-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0028_auto_20201227_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixed',
            name='ready_days',
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='show_dishes',
            field=models.CharField(default='Показать блюда', max_length=200, verbose_name='Показать блюда'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='show_dishes_he',
            field=models.CharField(default='Показать блюда', max_length=200, null=True, verbose_name='Показать блюда'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='show_dishes_ru',
            field=models.CharField(default='Показать блюда', max_length=200, null=True, verbose_name='Показать блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='friday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='friday2', to='MuscleFeed_main.Dish', verbose_name='Пятница стандартно второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='friday_other2',
            field=models.ManyToManyField(blank=True, null=True, related_name='friday_other2', to='MuscleFeed_main.Dish', verbose_name='Пятница все блюда второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='friday_price_female2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Пятница цена (в женской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='friday_price_male2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Пятница цена (в мужской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='monday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='monday2', to='MuscleFeed_main.Dish', verbose_name='Понедельник стандартно второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='monday_other2',
            field=models.ManyToManyField(blank=True, null=True, related_name='monday_other2', to='MuscleFeed_main.Dish', verbose_name='Понедельник все блюда второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='monday_price_female2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Понедельник цена (в женской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='monday_price_male2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Понедельник цена (в мужской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='saturday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='saturday2', to='MuscleFeed_main.Dish', verbose_name='Суббота стандартно второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='saturday_other2',
            field=models.ManyToManyField(blank=True, null=True, related_name='saturday_other2', to='MuscleFeed_main.Dish', verbose_name='Суббота все блюда второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='saturday_price_female2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Суббота цена (в женской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='saturday_price_male2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Суббота цена (в мужской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sunday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='sunday2', to='MuscleFeed_main.Dish', verbose_name='Воскресенье стандартно второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sunday_other2',
            field=models.ManyToManyField(blank=True, null=True, related_name='sunday_other2', to='MuscleFeed_main.Dish', verbose_name='Воскресенье все блюда второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sunday_price_female2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Воскресенье цена (в женской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sunday_price_male2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Воскресенье цена (в мужской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='thursday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='thursday2', to='MuscleFeed_main.Dish', verbose_name='Четверг стандартно второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='thursday_other2',
            field=models.ManyToManyField(blank=True, null=True, related_name='thursday_other2', to='MuscleFeed_main.Dish', verbose_name='Четверг все блюда второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='thursday_price_female2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Четверг цена (в женской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='thursday_price_male2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Четверг цена (в мужской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tuesday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='tuesday2', to='MuscleFeed_main.Dish', verbose_name='Вторник стандартно второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tuesday_other2',
            field=models.ManyToManyField(blank=True, null=True, related_name='tuesday_other2', to='MuscleFeed_main.Dish', verbose_name='Вторник все блюда второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tuesday_price_female2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Вторник цена (в женской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tuesday_price_male2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Вторник цена (в мужской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='wednesday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='wednesday2', to='MuscleFeed_main.Dish', verbose_name='Среда стандартно второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='wednesday_other2',
            field=models.ManyToManyField(blank=True, null=True, related_name='wednesday_other2', to='MuscleFeed_main.Dish', verbose_name='Среда все блюда второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='wednesday_price_female2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Среда цена (в женской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='menu',
            name='wednesday_price_male2',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Среда цена (в мужской версии) второй недели'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_friday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_friday2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда пятница'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_monday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_monday2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда понедельник второй недели'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_saturday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_saturday2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда суббота второй недели'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_sunday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_sunday2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда воскресенье второй недели'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_thursday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_thursday2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда четверг второй недели'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_tuesday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_tuesday2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда вторник второй недели'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_wednesday2',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_wednesday2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда среда второй недели'),
        ),
        migrations.AddField(
            model_name='order',
            name='excluding_weekday',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Исключенный день недели'),
        ),
        migrations.AlterField(
            model_name='accountpagesettings',
            name='pay',
            field=models.CharField(default='Оплатить онлайн', max_length=200, verbose_name='Оплатить онлайн'),
        ),
        migrations.AlterField(
            model_name='accountpagesettings',
            name='pay_he',
            field=models.CharField(default='Оплатить онлайн', max_length=200, null=True, verbose_name='Оплатить онлайн'),
        ),
        migrations.AlterField(
            model_name='accountpagesettings',
            name='pay_ru',
            field=models.CharField(default='Оплатить онлайн', max_length=200, null=True, verbose_name='Оплатить онлайн'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='friday_price_female',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Пятница цена (в женской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='friday_price_male',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Пятница цена (в мужской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='monday_price_female',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Понедельник цена (в женской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='monday_price_male',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Понедельник цена (в мужской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='saturday_price_female',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Суббота цена (в женской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='saturday_price_male',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Суббота цена (в мужской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sunday_price_female',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Воскресенье цена (в женской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sunday_price_male',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Воскресенье цена (в мужской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thursday_price_female',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Четверг цена (в женской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='thursday_price_male',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Четверг цена (в мужской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tuesday_price_female',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Вторник цена (в женской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tuesday_price_male',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Вторник цена (в мужской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='wednesday_price_female',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Среда цена (в женской версии)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='wednesday_price_male',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Среда цена (в мужской версии)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_date',
            field=models.DateField(blank=True, help_text='Включительно', null=True, verbose_name='Последняя дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
    ]
