# Generated by Django 3.1.2 on 2021-01-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0029_auto_20210111_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_ru_mp4', models.FileField(blank=True, null=True, upload_to='global/videos/ru/', verbose_name='Русский mp4')),
                ('video_ru_webm', models.FileField(blank=True, null=True, upload_to='global/videos/ru/', verbose_name='Русский webm')),
                ('video_ru_ogg', models.FileField(blank=True, null=True, upload_to='global/videos/ru/', verbose_name='Русский ogg')),
                ('video_he_mp4', models.FileField(blank=True, null=True, upload_to='global/videos/he/', verbose_name='Иврит mp4')),
                ('video_he_webm', models.FileField(blank=True, null=True, upload_to='global/videos/he/', verbose_name='Иврит webm')),
                ('video_he_ogg', models.FileField(blank=True, null=True, upload_to='global/videos/he/', verbose_name='Иврит ogg')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AddField(
            model_name='fixed',
            name='phone_number_he',
            field=models.CharField(max_length=20, null=True, verbose_name='Контактный номер телефона'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='phone_number_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Контактный номер телефона'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='info_video',
            field=models.CharField(default='Инструкция к сайту', max_length=200, verbose_name='Инструкция к сайту'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='info_video_he',
            field=models.CharField(default='Инструкция к сайту', max_length=200, null=True, verbose_name='Инструкция к сайту'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='info_video_ru',
            field=models.CharField(default='Инструкция к сайту', max_length=200, null=True, verbose_name='Инструкция к сайту'),
        ),
    ]
