# Generated by Django 3.1.2 on 2021-01-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0030_auto_20210111_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='select_days',
            field=models.CharField(default='Выберите количество дней', max_length=200, verbose_name='Выберите количество дней'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_days_he',
            field=models.CharField(default='Выберите количество дней', max_length=200, null=True, verbose_name='Выберите количество дней'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_days_ru',
            field=models.CharField(default='Выберите количество дней', max_length=200, null=True, verbose_name='Выберите количество дней'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_plan1_and_sex',
            field=models.CharField(default='Выберите цель питания и пол для взаимодействия с меню', max_length=200, verbose_name='Выберите цель питания и пол для взаимодействия с меню'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_plan2',
            field=models.CharField(default='Выберите план питания для похудения', max_length=200, verbose_name='Выберите план питания для похудения'),
        ),
    ]
