# Generated by Django 3.1.2 on 2021-01-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0031_auto_20210112_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed',
            name='notification_mails',
            field=models.TextField(blank=True, null=True, verbose_name='Email-ы для оповещений через Enter'),
        ),
    ]
