# Generated by Django 3.1.2 on 2021-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0034_auto_20210122_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpagesettings',
            name='change_address',
            field=models.CharField(default='Сменить адрес', max_length=200, verbose_name='Сменить адрес'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='change_address_he',
            field=models.CharField(default='Сменить адрес', max_length=200, null=True, verbose_name='Сменить адрес'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='change_address_ru',
            field=models.CharField(default='Сменить адрес', max_length=200, null=True, verbose_name='Сменить адрес'),
        ),
    ]
