# Generated by Django 3.1.2 on 2021-01-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0035_auto_20210127_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_called',
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
