# Generated by Django 3.1.2 on 2021-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0037_auto_20210204_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='balance_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='balance_image_webp',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='titan_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='titan_image_webp',
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='daily_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='account/plans/', verbose_name='Daily план фоновое изображение'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='daily_image_webp',
            field=models.ImageField(blank=True, editable=False, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='', verbose_name='Daily план фоновое изображение webp'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='gain_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='account/plans/', verbose_name='Gain план фоновое изображение'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='gain_image_webp',
            field=models.ImageField(blank=True, editable=False, help_text='Рекомендуемо 800x600, формат webp', null=True, upload_to='', verbose_name='Gain план фоновое изображение webp'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Comfort Fit', 'Comfort Fit'), ('Active Fit', 'Active Fit'), ('Express Fit', 'Express Fit'), ('Gain', 'Gain'), ('Daily', 'Daily'), ('Vegetarian', 'Vegetarian')], max_length=50, verbose_name='Меню'),
        ),
    ]
