# Generated by Django 3.1.2 on 2021-02-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0038_auto_20210204_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed',
            name='open_graph_description',
            field=models.CharField(default='', max_length=1000, verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_description_he',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_description_ru',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Open Graph description'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_image',
            field=models.ImageField(blank=True, help_text='1200x627px, основное содержимое (текст) в центре', null=True, upload_to='global/', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_image_he',
            field=models.ImageField(blank=True, help_text='1200x627px, основное содержимое (текст) в центре', null=True, upload_to='global/', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_image_ru',
            field=models.ImageField(blank=True, help_text='1200x627px, основное содержимое (текст) в центре', null=True, upload_to='global/', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_title',
            field=models.CharField(default='', max_length=200, verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_title_he',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Open Graph title'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='open_graph_title_ru',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Open Graph title'),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='base',
            field=models.CharField(help_text='Например: google.com', max_length=100, verbose_name='Домен сайта'),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='open_graph_site_name',
            field=models.CharField(default='', max_length=200, verbose_name='Open Graph site_name'),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='open_graph_site_name_he',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Open Graph site_name'),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='open_graph_site_name_ru',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Open Graph site_name'),
        ),
    ]
