# Generated by Django 3.1.2 on 2021-02-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0041_auto_20210209_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed',
            name='green_api_api_token_instance',
            field=models.CharField(blank=True, default='f0aae8ed17bb0218cc614361535f5e12994b1bc3ba664e14bc', help_text='ЛК Green API -> "Токен Api: (Эта строка)"', max_length=500, null=True, verbose_name='Green API Instance Token'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='green_api_id_instance',
            field=models.PositiveSmallIntegerField(blank=True, default=8771, help_text='ЛК Green API -> Сверху "Инстантс аккаунта Whatsapp" - "Whatsapp #(Это число)"', null=True, verbose_name='Green API Instance ID'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='notification_phones',
            field=models.TextField(blank=True, null=True, verbose_name='Номера телефонов Whatsapp для оповещений через Enter'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя и фамилия'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='phone',
            field=models.CharField(max_length=150, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
    ]
