# Generated by Django 3.1.2 on 2021-02-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0042_auto_20210209_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappertranslations',
            name='phone_10_error',
            field=models.CharField(default='Минимум 10 символов. Пример: +972001112222', max_length=200, verbose_name='Минимум 10 символов. Пример: +972001112222'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='phone_10_error_he',
            field=models.CharField(default='Минимум 10 символов. Пример: +972001112222', max_length=200, null=True, verbose_name='Минимум 10 символов. Пример: +972001112222'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='phone_10_error_ru',
            field=models.CharField(default='Минимум 10 символов. Пример: +972001112222', max_length=200, null=True, verbose_name='Минимум 10 символов. Пример: +972001112222'),
        ),
    ]
