# Generated by Django 3.1.2 on 2021-05-26 18:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0044_auto_20210213_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Полное название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Полное название')),
                ('name_he', models.CharField(max_length=50, null=True, verbose_name='Полное название')),
                ('short_description', models.CharField(default='Полезно для мышц', max_length=30, verbose_name='Короткое описание')),
                ('short_description_ru', models.CharField(default='Полезно для мышц', max_length=30, null=True, verbose_name='Короткое описание')),
                ('short_description_he', models.CharField(default='Полезно для мышц', max_length=30, null=True, verbose_name='Короткое описание')),
                ('extra_short_description', models.CharField(default='от 10$/мес', max_length=20, verbose_name='Окень короткое описание')),
                ('extra_short_description_ru', models.CharField(default='от 10$/мес', max_length=20, null=True, verbose_name='Окень короткое описание')),
                ('extra_short_description_he', models.CharField(default='от 10$/мес', max_length=20, null=True, verbose_name='Окень короткое описание')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=300, null=True, verbose_name='Описание')),
                ('description_he', models.CharField(max_length=300, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемо 920x1000, формат webp', null=True, upload_to='menu-types/', verbose_name='Фоновое изображение плана')),
                ('image_webp', models.ImageField(blank=True, editable=False, help_text='Рекомендуемо 920x1000, формат webp', null=True, upload_to='', verbose_name='Фоновое изображение плана webp')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Типы меню',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Политика конфеденциальности')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Политика конфеденциальности')),
                ('content_he', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Политика конфеденциальности')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Политика конфеденциальностии',
                'verbose_name_plural': 'Политика конфеденциальности',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='StatsPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Профилей')),
                ('profiles_change', models.IntegerField(blank=True, null=True, verbose_name='Новых профилей')),
                ('orders', models.PositiveIntegerField(blank=True, null=True, verbose_name='Заказов')),
                ('orders_change', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новых заказов')),
                ('avg_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Средний чек')),
                ('income', models.PositiveIntegerField(blank=True, null=True, verbose_name='Доход')),
                ('income_change', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новый доход')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Пользовательское соглашение')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Пользовательское соглашение')),
                ('content_he', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Пользовательское соглашение')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пользовательское соглашение',
                'verbose_name_plural': 'Пользовательские соглашения',
            },
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='active_fit_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='active_fit_image_webp',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='comfort_fit_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='comfort_fit_image_webp',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='daily_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='daily_image_webp',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='express_fit_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='express_fit_image_webp',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='gain_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='gain_image_webp',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='vegetarian_image',
        ),
        migrations.RemoveField(
            model_name='accountpagesettings',
            name='vegetarian_image_webp',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='calories_short',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='calories_short_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='calories_short_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='comfort_weight_loss',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='comfort_weight_loss_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='comfort_weight_loss_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='extrafast_weight_loss',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='extrafast_weight_loss_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='extrafast_weight_loss_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='fast_weight_loss',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='fast_weight_loss_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='fast_weight_loss_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='getting_muscles',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='getting_muscles_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='getting_muscles_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_for_bodybuilders',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_for_bodybuilders_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_for_bodybuilders_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_calories',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_calories_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_calories_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_image',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_image_webp',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_name',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_name_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_name_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_short_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_short_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan1_short_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_calories',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_calories_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_calories_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_image',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_image_webp',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_name',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_name_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_name_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_short_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_short_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan2_short_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_calories',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_calories_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_calories_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_image',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_image_webp',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_name',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_name_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_name_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_short_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_short_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan3_short_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_calories',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_calories_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_calories_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_image',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_image_webp',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_name',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_name_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_name_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_short_description',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_short_description_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='plan4_short_description_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='select_plan1_and_sex',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='select_sex',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='select_sex_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='select_sex_ru',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='vegetarian_menu',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='vegetarian_menu_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='vegetarian_menu_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day10_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day10_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day11_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day11_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day12_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day12_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day1_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day1_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day2_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day2_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day3_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day3_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day4_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day4_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day5_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day5_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day6_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day6_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day7_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day7_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day8_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day8_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day9_price_female',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day9_price_male',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='full_name_he',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='wrappertranslations',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='wrappertranslations',
            name='rules_he',
        ),
        migrations.RemoveField(
            model_name='wrappertranslations',
            name='rules_ru',
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='copy_referral_link',
            field=models.CharField(default='Скопировать ссылку', max_length=200, verbose_name='Скопировать ссылку'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='copy_referral_link_he',
            field=models.CharField(default='Скопировать ссылку', max_length=200, null=True, verbose_name='Скопировать ссылку'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='copy_referral_link_ru',
            field=models.CharField(default='Скопировать ссылку', max_length=200, null=True, verbose_name='Скопировать ссылку'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='get_promocode',
            field=models.CharField(default='Получить промокод', max_length=200, verbose_name='Получить промокод'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='get_promocode_he',
            field=models.CharField(default='Получить промокод', max_length=200, null=True, verbose_name='Получить промокод'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='get_promocode_info',
            field=models.CharField(default='Приведите друзей в наш сервис и мы щедро вас отблагодарим промокодом за каждого человека! Ваша реферальная ссылка: ', max_length=1000, verbose_name='Приведите друзей в наш сервис и мы щедро вас отблагодарим промокодом за каждого человека! Ваша реферальная ссылка: '),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='get_promocode_info_he',
            field=models.CharField(default='Приведите друзей в наш сервис и мы щедро вас отблагодарим промокодом за каждого человека! Ваша реферальная ссылка: ', max_length=1000, null=True, verbose_name='Приведите друзей в наш сервис и мы щедро вас отблагодарим промокодом за каждого человека! Ваша реферальная ссылка: '),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='get_promocode_info_ru',
            field=models.CharField(default='Приведите друзей в наш сервис и мы щедро вас отблагодарим промокодом за каждого человека! Ваша реферальная ссылка: ', max_length=1000, null=True, verbose_name='Приведите друзей в наш сервис и мы щедро вас отблагодарим промокодом за каждого человека! Ваша реферальная ссылка: '),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='get_promocode_ru',
            field=models.CharField(default='Получить промокод', max_length=200, null=True, verbose_name='Получить промокод'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='order_freeze_info',
            field=models.CharField(default='Ваша заявка на заморозку заказа принята, вскоре мы с вами свяжемся и обсудим подробности', max_length=200, verbose_name='Ваша заявка на заморозку заказа принята, вскоре мы с вами свяжемся и обсудим подробности'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='order_freeze_info_he',
            field=models.CharField(default='Ваша заявка на заморозку заказа принята, вскоре мы с вами свяжемся и обсудим подробности', max_length=200, null=True, verbose_name='Ваша заявка на заморозку заказа принята, вскоре мы с вами свяжемся и обсудим подробности'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='order_freeze_info_ru',
            field=models.CharField(default='Ваша заявка на заморозку заказа принята, вскоре мы с вами свяжемся и обсудим подробности', max_length=200, null=True, verbose_name='Ваша заявка на заморозку заказа принята, вскоре мы с вами свяжемся и обсудим подробности'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='referral_link_copy_success',
            field=models.CharField(default='Ссылка скопирована', max_length=200, verbose_name='Ссылка скопирована'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='referral_link_copy_success_he',
            field=models.CharField(default='Ссылка скопирована', max_length=200, null=True, verbose_name='Ссылка скопирована'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='referral_link_copy_success_info',
            field=models.CharField(default='Реферальная ссылка успешно скопирована!', max_length=200, verbose_name='Реферальная ссылка успешно скопирована!'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='referral_link_copy_success_info_he',
            field=models.CharField(default='Реферальная ссылка успешно скопирована!', max_length=200, null=True, verbose_name='Реферальная ссылка успешно скопирована!'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='referral_link_copy_success_info_ru',
            field=models.CharField(default='Реферальная ссылка успешно скопирована!', max_length=200, null=True, verbose_name='Реферальная ссылка успешно скопирована!'),
        ),
        migrations.AddField(
            model_name='accountpagesettings',
            name='referral_link_copy_success_ru',
            field=models.CharField(default='Ссылка скопирована', max_length=200, null=True, verbose_name='Ссылка скопирована'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='promocode_sale',
            field=models.IntegerField(default=20, verbose_name='Скидка с промокода'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='age',
            field=models.CharField(default='Возраст', max_length=200, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='age_he',
            field=models.CharField(default='Возраст', max_length=200, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='age_ru',
            field=models.CharField(default='Возраст', max_length=200, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='all_days',
            field=models.CharField(default='за заказ', max_length=200, verbose_name='за заказ'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='all_days_he',
            field=models.CharField(default='за заказ', max_length=200, null=True, verbose_name='за заказ'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='all_days_ru',
            field=models.CharField(default='за заказ', max_length=200, null=True, verbose_name='за заказ'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='calculate_calories',
            field=models.CharField(default='Расчитать калории', max_length=200, verbose_name='Расчитать калории'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='calculate_calories_he',
            field=models.CharField(default='Расчитать калории', max_length=200, null=True, verbose_name='Расчитать калории'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='calculate_calories_ru',
            field=models.CharField(default='Расчитать калории', max_length=200, null=True, verbose_name='Расчитать калории'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='calories_calculator',
            field=models.CharField(default='Калькулятор калорий', max_length=200, verbose_name='Калькулятор калорий'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='calories_calculator_he',
            field=models.CharField(default='Калькулятор калорий', max_length=200, null=True, verbose_name='Калькулятор калорий'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='calories_calculator_ru',
            field=models.CharField(default='Калькулятор калорий', max_length=200, null=True, verbose_name='Калькулятор калорий'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='female',
            field=models.CharField(default='Женский', max_length=200, verbose_name='Женский'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='female_he',
            field=models.CharField(default='Женский', max_length=200, null=True, verbose_name='Женский'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='female_ru',
            field=models.CharField(default='Женский', max_length=200, null=True, verbose_name='Женский'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='height',
            field=models.CharField(default='Рост', max_length=200, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='height_he',
            field=models.CharField(default='Рост', max_length=200, null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='height_ru',
            field=models.CharField(default='Рост', max_length=200, null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='male',
            field=models.CharField(default='Мужской', max_length=200, verbose_name='Мужской'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='male_he',
            field=models.CharField(default='Мужской', max_length=200, null=True, verbose_name='Мужской'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='male_ru',
            field=models.CharField(default='Мужской', max_length=200, null=True, verbose_name='Мужской'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='per_day',
            field=models.CharField(default='за день', max_length=200, verbose_name='за день'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='per_day_he',
            field=models.CharField(default='за день', max_length=200, null=True, verbose_name='за день'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='per_day_ru',
            field=models.CharField(default='за день', max_length=200, null=True, verbose_name='за день'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities',
            field=models.CharField(default='Физическая активность', max_length=200, verbose_name='Физическая активность'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities1',
            field=models.CharField(default='Нет физической активности', max_length=200, verbose_name='Нет физической активности'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities1_he',
            field=models.CharField(default='Нет физической активности', max_length=200, null=True, verbose_name='Нет физической активности'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities1_ru',
            field=models.CharField(default='Нет физической активности', max_length=200, null=True, verbose_name='Нет физической активности'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities2',
            field=models.CharField(default='2-3 раза в неделю неинтенсивных тренировок', max_length=200, verbose_name='2-3 раза в неделю неинтенсивных тренировок'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities2_he',
            field=models.CharField(default='2-3 раза в неделю неинтенсивных тренировок', max_length=200, null=True, verbose_name='2-3 раза в неделю неинтенсивных тренировок'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities2_ru',
            field=models.CharField(default='2-3 раза в неделю неинтенсивных тренировок', max_length=200, null=True, verbose_name='2-3 раза в неделю неинтенсивных тренировок'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities3',
            field=models.CharField(default='Постоянные интенсивные тренировки', max_length=200, verbose_name='Постоянные интенсивные тренировки'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities3_he',
            field=models.CharField(default='Постоянные интенсивные тренировки', max_length=200, null=True, verbose_name='Постоянные интенсивные тренировки'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities3_ru',
            field=models.CharField(default='Постоянные интенсивные тренировки', max_length=200, null=True, verbose_name='Постоянные интенсивные тренировки'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities_he',
            field=models.CharField(default='Физическая активность', max_length=200, null=True, verbose_name='Физическая активность'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='physical_activities_ru',
            field=models.CharField(default='Физическая активность', max_length=200, null=True, verbose_name='Физическая активность'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='promocode',
            field=models.CharField(default='Введите промокод, если есть', max_length=200, verbose_name='Введите промокод, если есть'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='promocode_he',
            field=models.CharField(default='Введите промокод, если есть', max_length=200, null=True, verbose_name='Введите промокод, если есть'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='promocode_ru',
            field=models.CharField(default='Введите промокод, если есть', max_length=200, null=True, verbose_name='Введите промокод, если есть'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose',
            field=models.CharField(default='Цель', max_length=200, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose1',
            field=models.CharField(default='Поддерживать вес', max_length=200, verbose_name='Поддерживать вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose1_he',
            field=models.CharField(default='Поддерживать вес', max_length=200, null=True, verbose_name='Поддерживать вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose1_ru',
            field=models.CharField(default='Поддерживать вес', max_length=200, null=True, verbose_name='Поддерживать вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose2',
            field=models.CharField(default='Сбросить вес', max_length=200, verbose_name='Сбросить вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose2_he',
            field=models.CharField(default='Сбросить вес', max_length=200, null=True, verbose_name='Сбросить вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose2_ru',
            field=models.CharField(default='Сбросить вес', max_length=200, null=True, verbose_name='Сбросить вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose3',
            field=models.CharField(default='Набрать массу', max_length=200, verbose_name='Набрать массу'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose3_he',
            field=models.CharField(default='Набрать массу', max_length=200, null=True, verbose_name='Набрать массу'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose3_ru',
            field=models.CharField(default='Набрать массу', max_length=200, null=True, verbose_name='Набрать массу'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose_he',
            field=models.CharField(default='Цель', max_length=200, null=True, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='purpose_ru',
            field=models.CharField(default='Цель', max_length=200, null=True, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='recommended_menus',
            field=models.CharField(default='Рекомендованые меню', max_length=200, verbose_name='Рекомендованые меню'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='result',
            field=models.CharField(default='Результат', max_length=200, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='result_he',
            field=models.CharField(default='Результат', max_length=200, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='result_ru',
            field=models.CharField(default='Результат', max_length=200, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_plan1',
            field=models.CharField(default='Выберите тип питания для взаимодействия с меню', max_length=200, verbose_name='Выберите тип питания для взаимодействия с меню'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='selected',
            field=models.CharField(default='Выбрано', max_length=200, verbose_name='Выбрано'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='selected_he',
            field=models.CharField(default='Выбрано', max_length=200, null=True, verbose_name='Выбрано'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='selected_ru',
            field=models.CharField(default='Выбрано', max_length=200, null=True, verbose_name='Выбрано'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='sex',
            field=models.CharField(default='Пол', max_length=200, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='sex_he',
            field=models.CharField(default='Пол', max_length=200, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='sex_ru',
            field=models.CharField(default='Пол', max_length=200, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='weight',
            field=models.CharField(default='Вес', max_length=200, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='weight_he',
            field=models.CharField(default='Вес', max_length=200, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='weight_ru',
            field=models.CharField(default='Вес', max_length=200, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='you_need_calories',
            field=models.CharField(default='Ваша дневная норма калорий:', max_length=200, verbose_name='Ваша дневная норма калорий:'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='you_need_calories_he',
            field=models.CharField(default='Ваша дневная норма калорий:', max_length=200, null=True, verbose_name='Ваша дневная норма калорий:'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='you_need_calories_ru',
            field=models.CharField(default='Ваша дневная норма калорий:', max_length=200, null=True, verbose_name='Ваша дневная норма калорий:'),
        ),
        migrations.AddField(
            model_name='menu',
            name='calories',
            field=models.IntegerField(default=2000, verbose_name='Калорий'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day10_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Десятый день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day11_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Одиннадцатый день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day12_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Двенадцатый день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day1_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Первый день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day2_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Второй день цена (в мужской версии'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day3_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Третий день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day4_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Четвертый день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day5_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Пятный день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day6_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Шестой день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day7_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Седьмой день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day8_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Восьмой день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day9_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='Девятый день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='1', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='name_he',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash_delivery', 'Наличкой курьеру'), ('card_delivery', 'Картой курьеру'), ('card_phone', 'Картой по телефону')], default='card_phone', max_length=100, verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_sale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка из-за промокода'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID профиля реферала'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referral_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID профиля реферала'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='calories_short',
            field=models.CharField(default='Ккал', max_length=200, verbose_name='Ккал'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='calories_short_he',
            field=models.CharField(default='Ккал', max_length=200, null=True, verbose_name='Ккал'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='calories_short_ru',
            field=models.CharField(default='Ккал', max_length=200, null=True, verbose_name='Ккал'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='card_delivery',
            field=models.CharField(default='Картой курьеру', max_length=200, verbose_name='Картой курьеру'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='card_delivery_he',
            field=models.CharField(default='Картой курьеру', max_length=200, null=True, verbose_name='Картой курьеру'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='card_delivery_ru',
            field=models.CharField(default='Картой курьеру', max_length=200, null=True, verbose_name='Картой курьеру'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='card_phone',
            field=models.CharField(default='Картой по телефону', max_length=200, verbose_name='Картой по телефону'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='card_phone_he',
            field=models.CharField(default='Картой по телефону', max_length=200, null=True, verbose_name='Картой по телефону'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='card_phone_ru',
            field=models.CharField(default='Картой по телефону', max_length=200, null=True, verbose_name='Картой по телефону'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='cash_delivery',
            field=models.CharField(default='Наличными курьеру', max_length=200, verbose_name='Наличными курьеру'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='cash_delivery_he',
            field=models.CharField(default='Наличными курьеру', max_length=200, null=True, verbose_name='Наличными курьеру'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='cash_delivery_ru',
            field=models.CharField(default='Наличными курьеру', max_length=200, null=True, verbose_name='Наличными курьеру'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='payment_type',
            field=models.CharField(default='Метод оплаты', max_length=200, verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='payment_type_he',
            field=models.CharField(default='Метод оплаты', max_length=200, null=True, verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='payment_type_ru',
            field=models.CharField(default='Метод оплаты', max_length=200, null=True, verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='privacy_policy',
            field=models.CharField(default='Политика конфеденциальности', max_length=200, verbose_name='Политика конфеденциальности'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='privacy_policy_he',
            field=models.CharField(default='Политика конфеденциальности', max_length=200, null=True, verbose_name='Политика конфеденциальности'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='privacy_policy_ru',
            field=models.CharField(default='Политика конфеденциальности', max_length=200, null=True, verbose_name='Политика конфеденциальности'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='user_agreement',
            field=models.CharField(default='Пользовательское соглашение', max_length=200, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='user_agreement_he',
            field=models.CharField(default='Пользовательское соглашение', max_length=200, null=True, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='user_agreement_ru',
            field=models.CharField(default='Пользовательское соглашение', max_length=200, null=True, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_he',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='select_plan2',
            field=models.CharField(default='Выберите план питания', max_length=200, verbose_name='Выберите план питания'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MuscleFeed_main.profile', verbose_name='Принадлежит профилю'),
        ),
    ]
