# Generated by Django 3.1.2 on 2021-05-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
