# Generated by Django 3.1.2 on 2021-05-26 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0048_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.IntegerField(blank=True, null=True, verbose_name='ID профиля реферала')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя Фамилия (Отчество)')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('payment_type', models.CharField(choices=[('cash_delivery', 'Наличкой курьеру'), ('card_delivery', 'Картой курьеру'), ('card_phone', 'Картой по телефону')], default='card_phone', max_length=100, verbose_name='Метод оплаты')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('first_date', models.DateField(help_text='Включительно', verbose_name='Первая дата')),
                ('days', models.IntegerField(verbose_name='Дней')),
                ('last_date', models.DateField(blank=True, help_text='Включительно', null=True, verbose_name='Последняя дата')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('changed_menu', models.BooleanField(default=False, editable=False, verbose_name='Измененное меню')),
                ('to_return', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Вернуть')),
                ('extend_allowed', models.BooleanField(default=True, verbose_name='Разрешено продление')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('promocode_sale', models.IntegerField(blank=True, null=True, verbose_name='Скидка из-за промокода')),
                ('dishes_day1', models.ManyToManyField(blank=True, null=True, related_name='dishes_day1', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда первый день')),
                ('dishes_day10', models.ManyToManyField(blank=True, null=True, related_name='dishes_day10', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда десятый день')),
                ('dishes_day11', models.ManyToManyField(blank=True, null=True, related_name='dishes_day11', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда одиннадцатый день')),
                ('dishes_day12', models.ManyToManyField(blank=True, null=True, related_name='dishes_day12', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двенадцатый день')),
                ('dishes_day2', models.ManyToManyField(blank=True, null=True, related_name='dishes_day2', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда второй день')),
                ('dishes_day3', models.ManyToManyField(blank=True, null=True, related_name='dishes_day3', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда третий день')),
                ('dishes_day4', models.ManyToManyField(blank=True, null=True, related_name='dishes_day4', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда четвертый день')),
                ('dishes_day5', models.ManyToManyField(blank=True, null=True, related_name='dishes_day5', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда пятый день')),
                ('dishes_day6', models.ManyToManyField(blank=True, null=True, related_name='dishes_day6', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда шестой день')),
                ('dishes_day7', models.ManyToManyField(blank=True, null=True, related_name='dishes_day7', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда седьмой день')),
                ('dishes_day8', models.ManyToManyField(blank=True, null=True, related_name='dishes_day8', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда восьмой день')),
                ('dishes_day9', models.ManyToManyField(blank=True, null=True, related_name='dishes_day9', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда девятый день')),
                ('freezes', models.ManyToManyField(blank=True, null=True, to='MuscleFeed_main.OrderFreeze', verbose_name='Заморозки')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MuscleFeed_main.menu', verbose_name='Меню')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MuscleFeed_main.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
