# Generated by Django 3.1.2 on 2021-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0049_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash_delivery', 'Наличкой курьеру'), ('card_delivery', 'Картой курьеру'), ('card_phone', 'Картой по телефону')], default='card_phone', max_length=100, null=True, verbose_name='Метод оплаты'),
        ),
    ]
