# Generated by Django 3.1.2 on 2021-05-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0050_auto_20210527_0504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatsPeriod',
        ),
    ]
