# Generated by Django 3.1.2 on 2021-05-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0051_delete_statsperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Профилей')),
                ('profiles_change', models.IntegerField(blank=True, null=True, verbose_name='Новых профилей')),
                ('orders', models.PositiveIntegerField(blank=True, null=True, verbose_name='Заказов')),
                ('orders_change', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новых заказов')),
                ('avg_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Средний чек')),
                ('income', models.PositiveIntegerField(blank=True, null=True, verbose_name='Доход')),
                ('income_change', models.PositiveIntegerField(blank=True, null=True, verbose_name='Новый доход')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
            ],
        ),
    ]
