# Generated by Django 3.1.2 on 2021-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0052_statsperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappertranslations',
            name='calories_short_start',
            field=models.CharField(default='от', max_length=200, verbose_name='от'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='calories_short_start_he',
            field=models.CharField(default='от', max_length=200, null=True, verbose_name='от'),
        ),
        migrations.AddField(
            model_name='wrappertranslations',
            name='calories_short_start_ru',
            field=models.CharField(default='от', max_length=200, null=True, verbose_name='от'),
        ),
    ]
