# Generated by Django 3.1.2 on 2021-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0053_auto_20210527_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='day10_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day11_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day12_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day1_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day2_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day3_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day4_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day5_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day6_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day7_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day8_price',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day9_price',
        ),
        migrations.AddField(
            model_name='menu',
            name='days14_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='14 дней цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='days1_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='1 день цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='days2_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='2 дня цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='days4_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='3 дня цена'),
        ),
        migrations.AddField(
            model_name='menu',
            name='days6_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='6 дней цена'),
        ),
    ]
