# Generated by Django 3.1.2 on 2021-06-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0055_auto_20210527_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='recommended_menus_he',
            field=models.CharField(default='Рекомендованые меню', max_length=200, null=True, verbose_name='Рекомендованые меню'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='recommended_menus_ru',
            field=models.CharField(default='Рекомендованые меню', max_length=200, null=True, verbose_name='Рекомендованые меню'),
        ),
        migrations.AddField(
            model_name='menu',
            name='home_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='menutype',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
    ]
