# Generated by Django 3.1.2 on 2021-06-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0056_auto_20210607_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='for_all',
            field=models.BooleanField(default=False, verbose_name='Для всех'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Код'),
        ),
    ]
