# Generated by Django 3.1.2 on 2021-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0057_auto_20210607_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_28',
            field=models.CharField(default='28 дней питания', max_length=200, verbose_name='28 дней питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_28_he',
            field=models.CharField(default='28 дней питания', max_length=200, null=True, verbose_name='28 дней питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_28_ru',
            field=models.CharField(default='28 дней питания', max_length=200, null=True, verbose_name='28 дней питания'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day13',
            field=models.ManyToManyField(blank=True, null=True, related_name='day13', to='MuscleFeed_main.Dish', verbose_name='Тринадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day13_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day13_other', to='MuscleFeed_main.Dish', verbose_name='Тринадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day14',
            field=models.ManyToManyField(blank=True, null=True, related_name='day14', to='MuscleFeed_main.Dish', verbose_name='Четырнадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day14_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day14_other', to='MuscleFeed_main.Dish', verbose_name='Четырнадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day15',
            field=models.ManyToManyField(blank=True, null=True, related_name='day15', to='MuscleFeed_main.Dish', verbose_name='Пятнадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day15_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day15_other', to='MuscleFeed_main.Dish', verbose_name='Пятнадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day16',
            field=models.ManyToManyField(blank=True, null=True, related_name='day16', to='MuscleFeed_main.Dish', verbose_name='Шестнадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day16_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day16_other', to='MuscleFeed_main.Dish', verbose_name='Шестнадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day17',
            field=models.ManyToManyField(blank=True, null=True, related_name='day17', to='MuscleFeed_main.Dish', verbose_name='Семнадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day17_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day17_other', to='MuscleFeed_main.Dish', verbose_name='Семнадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day18',
            field=models.ManyToManyField(blank=True, null=True, related_name='day18', to='MuscleFeed_main.Dish', verbose_name='Восемнадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day18_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day18_other', to='MuscleFeed_main.Dish', verbose_name='Восемнадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day19',
            field=models.ManyToManyField(blank=True, null=True, related_name='day19', to='MuscleFeed_main.Dish', verbose_name='Девятнадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day19_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day19_other', to='MuscleFeed_main.Dish', verbose_name='Девятнадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day20',
            field=models.ManyToManyField(blank=True, null=True, related_name='day20', to='MuscleFeed_main.Dish', verbose_name='Двадцатый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day20_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day20_other', to='MuscleFeed_main.Dish', verbose_name='Двадцатый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day21',
            field=models.ManyToManyField(blank=True, null=True, related_name='day21', to='MuscleFeed_main.Dish', verbose_name='Двадцать первый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day21_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day21_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать первый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day22',
            field=models.ManyToManyField(blank=True, null=True, related_name='day22', to='MuscleFeed_main.Dish', verbose_name='Двадцать второй день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day22_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day22_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать второй день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day23',
            field=models.ManyToManyField(blank=True, null=True, related_name='day23', to='MuscleFeed_main.Dish', verbose_name='Двадцать третий день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day23_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day23_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать третий день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day24',
            field=models.ManyToManyField(blank=True, null=True, related_name='day24', to='MuscleFeed_main.Dish', verbose_name='Двадцать четвертый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day24_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day24_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать четвертый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day25',
            field=models.ManyToManyField(blank=True, null=True, related_name='day25', to='MuscleFeed_main.Dish', verbose_name='Двадцать пятый день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day25_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day25_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать пятый день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day26',
            field=models.ManyToManyField(blank=True, null=True, related_name='day26', to='MuscleFeed_main.Dish', verbose_name='Двадцать шестой день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day26_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day26_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать шестой день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day27',
            field=models.ManyToManyField(blank=True, null=True, related_name='day27', to='MuscleFeed_main.Dish', verbose_name='Двадцать седьмой день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day27_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day27_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать седьмой день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day28',
            field=models.ManyToManyField(blank=True, null=True, related_name='day28', to='MuscleFeed_main.Dish', verbose_name='Двадцать восьмой день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day28_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day28_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать восьмой день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='days28_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, verbose_name='28 дней цена'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day13',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day13', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда тринадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day14',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day14', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда четырнадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day15',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day15', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда пятнадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day16',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day16', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда шестнадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day17',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day17', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда семнадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day18',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day18', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда восемнадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day19',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day19', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда девятнадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day20',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day20', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцатый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day21',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day21', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать первый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day22',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day22', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать второй день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day23',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day23', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать третий день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day24',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day24', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать четвертый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day25',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day25', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать пятый день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day26',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day26', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать шестой день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day27',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day27', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать седьмой день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day28',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day28', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать восьмой день'),
        ),
        migrations.AlterField(
            model_name='changepersonaldatarequest',
            name='type',
            field=models.CharField(choices=[('name', 'Имя'), ('surname', 'Фамилия'), ('phone', 'Телефон'), ('address', 'Адрес')], default='name', max_length=13, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='admin_name',
            field=models.CharField(max_length=120, verbose_name='Название для админа'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_he',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('second-breakfast', 'Второй завтрак'), ('lunch', 'Обед'), ('high-tea', 'Полдник'), ('dinner', 'Ужин'), ('drink', 'Напиток')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day1',
            field=models.ManyToManyField(blank=True, null=True, related_name='day1', to='MuscleFeed_main.Dish', verbose_name='Первый 1 стандартно'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='day1_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day1_other', to='MuscleFeed_main.Dish', verbose_name='Первый 1 все блюда'),
        ),
    ]
