# Generated by Django 3.1.2 on 2021-09-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0059_auto_20210924_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='days26_price',
            new_name='days28_price',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_days_26',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_days_26_he',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='meal_days_26_ru',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_28',
            field=models.CharField(default='28 дней питания', max_length=200, verbose_name='26 дней питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_28_he',
            field=models.CharField(default='28 дней питания', max_length=200, null=True, verbose_name='26 дней питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='meal_days_28_ru',
            field=models.CharField(default='28 дней питания', max_length=200, null=True, verbose_name='26 дней питания'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day27',
            field=models.ManyToManyField(blank=True, null=True, related_name='day27', to='MuscleFeed_main.Dish', verbose_name='Двадцать шестой день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day27_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day27_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать шестой день все блюда'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day28',
            field=models.ManyToManyField(blank=True, null=True, related_name='day28', to='MuscleFeed_main.Dish', verbose_name='Двадцать шестой день стандартно'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day28_other',
            field=models.ManyToManyField(blank=True, null=True, related_name='day28_other', to='MuscleFeed_main.Dish', verbose_name='Двадцать шестой день все блюда'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day27',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day27', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать седьмой день'),
        ),
        migrations.AddField(
            model_name='order',
            name='dishes_day28',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes_day28', to='MuscleFeed_main.Dish', verbose_name='Выбранные блюда двадцать восьмой день'),
        ),
    ]
