# Generated by Django 3.1.2 on 2021-09-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MuscleFeed_main', '0061_auto_20210924_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='select_plan1_he',
            field=models.CharField(default='Выберите тип питания для взаимодействия с меню', max_length=200, null=True, verbose_name='Выберите тип питания для взаимодействия с меню'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_plan1_ru',
            field=models.CharField(default='Выберите тип питания для взаимодействия с меню', max_length=200, null=True, verbose_name='Выберите тип питания для взаимодействия с меню'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_plan2_he',
            field=models.CharField(default='Выберите план питания', max_length=200, null=True, verbose_name='Выберите план питания'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='select_plan2_ru',
            field=models.CharField(default='Выберите план питания', max_length=200, null=True, verbose_name='Выберите план питания'),
        ),
    ]
